# Generated by Django 5.1.3 on 2024-11-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualiser', '0002_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('nodeId', models.AutoField(primary_key=True, serialize=False)),
                ('nodeVal', models.IntegerField()),
                ('leftChild', models.IntegerField()),
                ('rightChild', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tree',
            name='root',
            field=models.IntegerField(),
        ),
    ]
